eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

#        Product Service
        - id: PRODUCT
          uri: http://localhost:8082/api/
          predicates:
            - Path=/api/**

#       AUTH
        - id: AUTH
          uri: http://localhost:8083/api/auth/
          predicates:
            - Path=/api/auth/**

#       Order
        - id: ORDER
          uri: http://localhost:8084/api/orders/
          predicates:
            - Path=/api/orders/**

#        Payment
        - id: PAYMENT
          uri: http://localhost:8085/api/payment/
          predicates:
            - Path=/api/payment/**

#       Rating Service
        - id: SERVICE
          uri: http://localhost:8086/api/ratings/
          predicates:
            - Path=/api/ratings/**

#        Product Details Service
        - id: PRODUCT DETAILS
          uri: http://localhost:8087/products/details/
          predicates:
            - Path=/products/details/**

#        Category
        - id: CATEGORY
          uri: http://localhost:8088/api/categories/
          predicates:
            - Path=/api/categories/**

#        Cart
        - id: CART
          uri: http://localhost:8089/api/cart/
          predicates:
            - Path=/api/cart/**